// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Achievement: typeof import('./src/components/Icons/achievement.vue')['default']
    Artifact: typeof import('./src/components/Icons/artifact.vue')['default']
    BuildInfo: typeof import('./src/components/BuildInfo.vue')['default']
    Cocogoat: typeof import('./src/components/Icons/cocogoat.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FloatWindow: typeof import('./src/components/FloatWindow.vue')['default']
    FloatWindow2: typeof import('./src/components/FloatWindow2.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}

export { }
